# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clarifaiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapoetry
	pod 'Clarifai'
	pod 'SnapKit', '~> 3.0.0’
    
end
